### ISSUE TITLE
support for @Nested 

### ISSUE THREAD

**Issue by vincent-fuchs** [grzegorz-aniol/junit5-watcher#4]
Hi,

Using v1.0.0, I am facing same issue as described in https://github.com/grzegorz-aniol/junit5-watcher/issues/2 , but in my case it's because my tests are using `org.junit.jupiter.api.Nested`. Then I get : 

java.lang.RuntimeException: Cannot find time mark for type AFTER_EACH
	at pl.appga.junit5watcher.BenchmarkExtension.getTimeMark-Agz8NFE(BenchmarkExtension.kt:116)
	at pl.appga.junit5watcher.BenchmarkExtension.measureAndSaveMetric(BenchmarkExtension.kt:90)
	at pl.appga.junit5watcher.BenchmarkExtension.afterAll(BenchmarkExtension.kt:85)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

Is it the same root cause and it will be fixed with next release ? 

Note : the report gets generated though, with one record for each `@Nested` . There's no record for individual tests, and I don't know if it's intended or not ;-)

**Comment by grzegorz-aniol** [comment]
Thank @vincent-fuchs for reporting this case. The previous fix should solve the problem as well, but I will add additional tests to be sure. I will release next version today or tomorrow morning.

**Comment by vincent-fuchs** [comment]
I confirm it now works with v1.1 . thanks !
